# Generated by Django 5.1.5 on 2026-02-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=200)),
                ('salary', models.BigIntegerField()),
                ('department', models.CharField(max_length=200)),
                ('joining', models.DateField()),
                ('full_time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('manager_employee', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=40)),
                ('employee_id', models.IntegerField()),
            ],
        ),
    ]
