# Generated by Django 5.1.5 on 2026-03-05 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee_attendence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Bank_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('acc_no', models.BigIntegerField()),
                ('ifsc_code', models.CharField(max_length=15)),
                ('holder_name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('branch', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aadhar', models.FileField(upload_to='')),
                ('pan', models.FileField(upload_to='')),
                ('ssc', models.FileField(upload_to='')),
                ('inter', models.FileField(upload_to='')),
                ('graduation', models.FileField(upload_to='')),
                ('photo', models.FileField(upload_to='')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_other_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.BigIntegerField()),
                ('Gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('this_month_pay', models.BigIntegerField()),
                ('pf_deduction', models.FloatField()),
                ('total_working_Days', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_statuory_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(max_length=10)),
                ('pf_uan', models.CharField(max_length=30)),
                ('profesional_tax', models.CharField(max_length=100)),
                ('lwf_status', models.CharField(max_length=100)),
                ('esic_status', models.CharField(max_length=100)),
                ('esic_ip_number', models.BigIntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('number_of_days', models.IntegerField()),
                ('remaining_leaves', models.IntegerField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('basic_salary', models.FloatField()),
                ('gross_salary', models.FloatField()),
                ('pf_amount', models.FloatField()),
                ('professional_tax', models.FloatField()),
                ('lop_days', models.IntegerField()),
                ('lop_amount', models.FloatField()),
                ('net_salary', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_registration')),
            ],
        ),
    ]
