# Generated by Django 5.1.5 on 2026-03-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employee_bank_details_employee_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
