# Generated by Django 5.1.5 on 2026-03-07 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employee_main_files_delete_employee_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_attendence',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='employee_attendence',
            name='checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='employee_attendence',
            unique_together={('name', 'date')},
        ),
    ]
