# Generated by Django 5.1.5 on 2026-03-07 05:57

from django.db import migrations
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_employee_attendence_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='Employee_attendence',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate))
    ]
