# Generated by Django 5.1.5 on 2026-03-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_date_to_attendence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee_attendence',
            unique_together=set(),
        ),
    ]
