# Generated by Django 5.1.5 on 2026-03-07 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_employee_attendence_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee_attendence',
            unique_together={('name', 'date')},
        ),
    ]
