# Generated by Django 5.1.5 on 2026-03-07 06:05

from django.db import migrations

from django.db import migrations, models
import django.utils.timezone
class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_employee_attendence_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_attendence',
            name = 'date_today',
            field=models.DateField(default=django.utils.timezone.localdate),
        )]
