# Generated by Django 5.1.5 on 2026-03-07 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_add_date_to_attendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_attendence',
            name='date_today',
        ),
    ]
