# Generated by Django 5.1.5 on 2026-03-07 06:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_employee_attendence_date_today'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_attendence_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('checkin', models.DateTimeField(blank=True, null=True)),
                ('checkout', models.DateTimeField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee_registration')),
            ],
            options={
                'unique_together': {('name', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='Employee_attendence',
        ),
    ]
