# Generated by Django 5.1.5 on 2026-03-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_employee_attendence_details_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee_attendence_details',
            unique_together=set(),
        ),
    ]
