# Generated by Django 5.1.5 on 2026-03-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_employee_attendence_details_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee_attendence_details',
            unique_together={('name', 'date')},
        ),
    ]
