# Generated by Django 5.1.5 on 2026-03-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_employee_attendence_details_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_attendence_details',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
