# Generated by Django 5.1.5 on 2026-03-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_employee_attendence_details_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_other_details',
            name='Gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee_other_details',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee_other_details',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee_other_details',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_other_details',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
