# Generated by Django 5.1.5 on 2026-03-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_employee_other_details_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_bank_details',
            name='acc_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_bank_details',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee_bank_details',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee_bank_details',
            name='holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee_bank_details',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee_bank_details',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
