# Generated by Django 5.1.5 on 2026-03-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_employee_bank_details_acc_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_other_details',
            name='marital_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
