# Generated by Django 4.2.7 on 2026-03-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_employee_other_details_marital_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_id', models.CharField(max_length=50)),
                ('employee', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('asset_type', models.CharField(max_length=50)),
                ('model_details', models.CharField(max_length=200)),
                ('assigned_date', models.DateField()),
                ('status', models.CharField(default='assigned', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=100)),
                ('asset_category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
