# Generated by Django 4.2.7 on 2026-03-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_asset_assetrequest_returnasset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetrequest',
            old_name='description',
            new_name='model_detail',
        ),
    ]
