# Generated by Django 4.2.7 on 2026-03-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_employee_break_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_statuory_information',
            name='esic_ip_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_statuory_information',
            name='esic_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee_statuory_information',
            name='lwf_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee_statuory_information',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee_statuory_information',
            name='pf_uan',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee_statuory_information',
            name='profesional_tax',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
