# Generated by Django 4.2.7 on 2026-03-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_employee_statuory_information_esic_ip_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_registration',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
